<div>
  <div class="attettion p-4 m-4 bg-white">
    copy ctrl-C any Ancient Greek text (UTF-8) anywhere and ctrl-V, or just V here, as if you pasting it. Then click a word
  </div>
  <p >2:1 -
 <span class="wf">Τοῦ</span>
 <span class="wf">δὲ</span>
 <span class="wf">Ἰησοῦ</span>
 <span class="wf">γεννηθέντος</span>
 <span class="wf">ἐν</span>
 <span class="wf">Βηθλέεμ</span>
 <span class="wf">τῆς</span>
 <span class="wf">Ἰουδαίας</span>
 <span class="wf">ἐν</span>
 <span class="wf">ἡμέραις</span>
 <span class="wf">Ἡρῴδου</span>
 <span class="wf">τοῦ</span>
 <span class="wf">βασιλέως,</span>
 <span class="wf">ἰδοὺ </span>
 <span class="wf">μάγοι</span>
 <span class="wf">ἀπὸ</span>
 <span class="wf">ἀνατολῶν</span>
 <span class="wf">παρεγένοντο</span>
 <span class="wf">εἰς</span>
 <span class="wf">Ἱεροσόλυμα</span>
 <span class="wf">λέγοντες</span>, 2:2 -
 <span class="wf">ποῦ</span>
 <span class="wf">ἐστιν</span>
 <span class="wf">ὁ</span>
 <span class="wf">τεχθεὶς</span>
 <span class="wf">βασιλεὺς</span>
 <span class="wf">τῶν</span>
 <span class="wf">Ἰουδαίων;</span>
 <span class="wf">εἴδομεν</span>
 <span class="wf">γὰρ</span>
 <span class="wf">αὐτοῦ</span>
 <span class="wf">τὸν</span>
 <span class="wf">ἀστέρα</span>
 <span class="wf">ἐν</span>
 <span class="wf">τῇ</span>
 <span class="wf">ἀνατολῇ</span>,
 <span class="wf">καὶ</span>
 <span class="wf">ἤλθομεν</span>
 <span class="wf">προσκυνῆσαι</span>
 <span class="wf">αὐτῷ</span>. 2:3 -
 <span class="wf">ἀκούσας</span>
 <span class="wf">δὲ</span>
 <span class="wf">ὁ</span>
 <span class="wf">βασιλεὺς</span>
 <span class="wf">Ἡρῴδης</span>
 <span class="wf">ἐταράχθη</span>,
 <span class="wf">καὶ</span>
 <span class="wf">πᾶσα</span>
 <span class="wf">Ἱεροσόλυμα</span>
 <span class="wf">κατ'</span>
 <span class="wf">αὐτοῦ</span>. 2:4 -
 <span class="wf">καὶ</span>
 <span class="wf">συναγαγὼν</span>
 <span class="wf">πάντας</span>
 <span class="wf">τοὺς</span>
 <span class="wf">ἀρχιερεῖς</span>
 <span class="wf">καὶ</span>
 <span class="wf">γραμματεῖς</span>
 <span class="wf">τοῦ</span>
 <span class="wf">λαοῦ</span>
 <span class="wf">ἐπυνθάνετο</span>
 <span class="wf">παρ'</span>
 <span class="wf">αὐτῶν</span>
 <span class="wf">ποῦ</span>
 <span class="wf">ὁ</span>
 <span class="wf">χριστὸς</span>
 <span class="wf">γεννᾶται</span>. 2:5 -
 <span class="wf">οἱ</span>
 <span class="wf">δὲ</span>
 <span class="wf">εἶπαν</span>
 <span class="wf">αὐτῷ</span>
 <span class="wf">ἐν</span>
 <span class="wf">Βηθλέεμ</span>
 <span class="wf">τῆς</span>
 <span class="wf">Ἰουδαίας.</span>
 <span class="wf">οὕτως</span>
 <span class="wf">γὰρ</span>
 <span class="wf">γέγραπται</span>
 <span class="wf">διὰ</span>
 <span class="wf">τοῦ</span>
 <span class="wf">προφήτου</span>, 2:6 -
 <span class="wf">καὶ</span>
 <span class="wf">σὺ</span>
 <span class="wf">Βηθλέεμ</span>,
 <span class="wf">γῆ</span>
 <span class="wf">Ἰούδα</span>,
 <span class="wf">οὐδαμῶς</span>
 <span class="wf">ἐλαχίστη</span>
 <span class="wf">εἶ</span>
 <span class="wf">ἐν</span>
 <span class="wf">τοῖς</span>
 <span class="wf">ἡγεμόσιν</span>
 <span class="wf">Ἰούδα</span>
 <span class="wf">ἐκ</span>
 <span class="wf">σοῦ</span>
 <span class="wf">γὰρ</span>
 <span class="wf">ἐξελεύσεται</span>
 <span class="wf">ἡγούμενος</span>,
 <span class="wf">ὅστις</span>
 <span class="wf">ποιμανεῖ</span>
 <span class="wf">τὸν</span>
 <span class="wf">λαόν</span>
 <span class="wf">μου</span>
 <span class="wf">τὸν</span>
 <span class="wf">Ἰσραήλ</span> 2:7 -
 <span class="wf">Τότε</span>
 <span class="wf">Ἡρῴδης</span>
 <span class="wf">λάθρα</span>
 <span class="wf">καλέσας</span>
 <span class="wf">τοὺς</span>
 <span class="wf">μάγους</span>
 <span class="wf">ἠκρίβωσεν</span>
 <span class="wf">παρ'</span>
 <span class="wf">αὐτῶν</span>
 <span class="wf">τὸν</span>
 <span class="wf">χρόνον</span>
 <span class="wf">τοῦ</span>
 <span class="wf">φαινομένου</span>
 <span class="wf">ἀστέρος</span>. 2:8 -
 <span class="wf">καὶ</span>
 <span class="wf">πέμψας</span>
 <span class="wf">αὐτοὺς</span>
 <span class="wf">εἰς</span>
 <span class="wf">Βηθλέεμ</span>
 <span class="wf">εἶπεν</span>
 <span class="wf">πορευθέντες</span>
 <span class="wf">ἐξετάσατε</span>
 <span class="wf">ἀκριβῶς</span>
 <span class="wf">περὶ</span>
 <span class="wf">τοῦ</span>
 <span class="wf">παιδίου.</span>
 <span class="wf">ἐπὰν</span>
 <span class="wf">δὲ</span>
 <span class="wf">εὕρητε</span>,
 <span class="wf">ἀπαγγείλατέ</span>
 <span class="wf">μοι</span>,
 <span class="wf">ὅπως</span>
 <span class="wf">κάγὼ</span>
 <span class="wf">ἐλθὼν</span>
 <span class="wf">προσκυνήσω</span>
 <span class="wf">αὐτῷ</span>. 2:9 -
 <span class="wf">οἱ</span>
 <span class="wf">δὲ</span>
 <span class="wf">ἀκούσαντες</span>
 <span class="wf">τοῦ</span>
 <span class="wf">βασιλέως</span>
 <span class="wf">ἐπορεύθησαν.</span>
 <span class="wf">καὶ</span>
 <span class="wf">ἰδοὺ</span>
 <span class="wf">ὁ</span>
 <span class="wf">ἀστήρ</span>,
 <span class="wf">ὃν</span>
 <span class="wf">εἶδον</span>
 <span class="wf">ἐν</span>
 <span class="wf">τῇ</span>
 <span class="wf">ἀνατολῇ</span>,
 <span class="wf">προῆγεν</span>
 <span class="wf">αὐτοὺς</span>
 <span class="wf">ἕως</span>
 <span class="wf">ἐλθὼν</span>
 <span class="wf">ἐστάθη</span>
 <span class="wf">ἐπάνω</span>
 <span class="wf">οὗ</span>
 <span class="wf">ἦν</span>
 <span class="wf">τὸ</span>
 <span class="wf">παιδίον</span>. 2:10 -
 <span class="wf">ἰδόντες</span>
 <span class="wf">δὲ</span>
 <span class="wf">τὸν</span>
 <span class="wf">ἀστέρα</span>
 <span class="wf">ἐχάρησαν</span>
 <span class="wf">χαρὰν</span>
 <span class="wf">μεγάλην</span>
 <span class="wf">σφόδρα</span>. 2:11 -
 <span class="wf">καὶ</span>
 <span class="wf">ἐλθόντες</span>
 <span class="wf">εἰς</span>
 <span class="wf">τὴν</span>
 <span class="wf">οἰκίαν</span>
 <span class="wf">εἶδον</span>
 <span class="wf">τὸ</span>
 <span class="wf">παιδίον</span>
 <span class="wf">μετὰ</span>
 <span class="wf">Μαρίας</span>
 <span class="wf">τῆς</span>
 <span class="wf">μητρὸς</span>
 <span class="wf">αὐτοῦ.</span>
 <span class="wf">καὶ</span>
 <span class="wf">πεσόντες</span>
 <span class="wf">προσεκύνησαν</span>
 <span class="wf">αὐτῷ</span>,
 <span class="wf">καὶ</span>
 <span class="wf">ἀνοίξαντες</span>
 <span class="wf">τοὺς</span>
 <span class="wf">θησαυροὺς</span>
 <span class="wf">αὐτῶν</span>
 <span class="wf">προσήνεγκαν</span>
 <span class="wf">αὐτῷ</span>
 <span class="wf">δῶρα</span>,
 <span class="wf">χρυσὸν</span>
 <span class="wf">καὶ</span>
 <span class="wf">λίβανον</span>
 <span class="wf">καὶ</span>
 <span class="wf">σμύρναν</span>. 2:12 -
 <span class="wf">καὶ</span>
 <span class="wf">χρηματισθέντες</span>
 <span class="wf">κατ'</span>
 <span class="wf">ὄναρ</span>
 <span class="wf">μὴ</span>
 <span class="wf">ἀνακάμψαι</span>
 <span class="wf">πρὸς</span>
 <span class="wf">Ἡρῴδην</span>,
 <span class="wf">δι'</span>
 <span class="wf">ἄλλης</span>
 <span class="wf">ὁδοῦ</span>
 <span class="wf">ἀνεχώρησαν</span>
 <span class="wf">εἰς</span>
 <span class="wf">τὴν</span>
 <span class="wf">χώραν</span>
 <span class="wf">αὐτῶν</span>.
  </p>
  <p>
    Mark 10:14b
  </p>

  <p>
 <span class="wf">Ἄφετε</span>
 <span class="wf">τὰ</span>
 <span class="wf">παιδία</span>
 <span class="wf">ἔρχεσθαι</span>
 <span class="wf">πρός</span>
 <span class="wf">με</span>,
  </p>
  <p>
 <span class="wf">μὴ</span>
 <span class="wf">κωλύετε</span>
 <span class="wf">αὐτά·</span>
  </p>
  <p>

 <span class="wf">τῶν</span>
 <span class="wf">γὰρ</span>
 <span class="wf">τοιούτων</span>
 <span class="wf">ἐστὶν</span>
 <span class="wf">ἡ</span>
 <span class="wf">βασιλεία</span>
 <span class="wf">τοῦ</span>
 <span class="wf">θεοῦ.</span>
  </p>
</div>
